name: Client CI

on: [push]

jobs:
  Build-Client-Docker-Image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Prepare Environment
        run: git submodule update --init --recursive

      - name: Build Client Docker Image
        run: docker build bookchain-client -t bookchain-client

  Test-Client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Prepare Environment
        run: |
          git submodule update --init --recursive
          cd bookchain-client
          yarn install

      - name: Run Tests
        run: |
          cd bookchain-client
          yarn test --coverage --watchAll=false

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./bookchain-client/coverage/lcov.info

  Lint-Client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Prepare Environment
        run: |
          git submodule update --init --recursive
          cd bookchain-client
          yarn install

      - name: Run Tests
        run: |
          cd bookchain-client
          yarn lint-check
          yarn pretty-check
