name: Miner CI

on: [push]

jobs:
  Build-Miner-Docker-Image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Prepare Environment
        run: git submodule update --init --recursive

      - name: Build Miner Docker Image
        run: docker build bookchain-miner -t bookchain-miner

  Lint-Miner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Prepare Environment
        # Seems like clang is broken in Ubuntu so I have to do this for now
        run: |
          git submodule update --init --recursive
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key 2>/dev/null | sudo apt-key add -
          sudo add-apt-repository 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main' -y
          sudo apt-get update -q
          sudo apt-get install -y clang-9 lld-9 libc++-9-dev libc++abi-9-dev clang-tools-9 clang-format-9

      - name: Run clang-format on Miner
        run: |
          cd bookchain-miner
          sed 's/clang-format/clang-format-9/' tools/checkformat.sh > tools/checkformatfixed.sh
          chmod +x tools/checkformatfixed.sh
          tools/checkformatfixed.sh
